version: 1.0.{build}
configuration: Release

image: Visual Studio 2017

branches:
  only:
  - master
  
init:
  - git config --global core.autocrlf input
  
clone_folder: c:\projects\tictactoe

shallow_clone: true
  
dotnet_csproj:
  file: '.tttGrd/tttGrd.csproj'
  version: '{version}'
  package_version: '{version}'
  
before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov
  
build_script:
  - msbuild /verbosity:quiet "tttGrd/tttGrd.csproj"
  
test_script:
  - msbuild /verbosity:quiet "tttGrd.Test/tttGrd.Test.csproj"
  - nunit3-console "c:\projects\tictactoe\tttGrd.Test\bin\Release\tttGrd.Test.dll"
  - OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"c:\projects\tictactoe\tttGrd.Test\bin\Release\tttGrd.Test.dll" -filter:"+[*]* -[*.*Tests*]*" -output:"ttGrd_coverage.xml"
  - type ttGrd_coverage.xml

after_test:
  - codecov -f ttGrd_coverage.xml
    
artifacts:
  - path: ttGrd_coverage.xml
