version: 1.0.{build}
configuration: Release

image: Visual Studio 2017

branches:
  only:
  - master
  
init:
  - git config --global core.autocrlf input
  
clone_folder: c:\projects\tictactoe

shallow_clone: true
  
dotnet_csproj:
  file: './src/tttGrd.Api/tttGrd.Api.csproj'
  version: '{version}'
  package_version: '{version}'
  
before_build:
  - cmd: cd src
  - nuget restore 
  - choco install opencover.portable
  - choco install codecov
  
build_script:
  - msbuild /verbosity:quiet "tttGrd.Api/tttGrd.Api.csproj"
  
test_script:
  - msbuild /verbosity:quiet "tttGrd.Api.Tests/tttGrd.Api.Tests.csproj"
  - OpenCover.Console.exe -register:user -hideskipped:filter -target:"nunit3-console.exe" -targetargs:"c:\projects\tictactoe\src\tttGrd.Api.Tests\bin\Release\tttGrd.Api.Tests.dll" -filter:"+[*]* -[*.Tests]*" -output:"ttGrd_coverage.xml"

after_test:
  - codecov -f "c:\projects\tictactoe\src\ttGrd_coverage.xml"

artifacts:
  - path: '.\src\ttGrd_coverage.xml'
