version: 1.0.{build}
configuration: Release

image: Visual Studio 2017

#pull_requests:
  #do_not_increment_build_number: true

#nuget:
  #disable_publish_on_pr: true

branches:
  only:
  - master
  
init:
  - git config --global core.autocrlf input
  
clone_folder: c:\projects\tictactoe

shallow_clone: true
  
dotnet_csproj:
  #patch: true
  file: '.tttGrd/tttGrd.csproj'
  version: '{version}'
  package_version: '{version}'
  
before_build:
  #- dotnet --version
  #- dotnet restore tttGrd.sln --verbosity m
  #- choco install opencover.portable
  #- choco install codecov
  - nuget restore
  
build_script:
  #- dotnet publish ./tttGrd/tttGrd.csproj
  - msbuild /verbosity:quiet "tttGrd/tttGrd.csproj"
  
test_script:
  - msbuild /verbosity:quiet "tttGrd.Test/tttGrd.Test.csproj"
  - nunit3-console "c:\projects\tictactoe\tttGrd.Test\bin\Release\tttGrd.Test.dll"
  #- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\MSTest.exe" -targetargs:"YourTestDll -noshadow" -output:"coverage.xml" -filter:"+[YourSUTNamepace*]* -[YourTestNamespace*]*"

#build:
  #verbosity: minimal
  #publish_wap: true
